services:
    bot:
        build:
            context: .
        container_name: account-bot
        depends_on:
            gluetun:
                condition: service_started
        environment:
            TZ: ${TZ:-UTC}
            USERNAME: ${USERNAME:?error}
            PASSWORD: ${PASSWORD:?error}
            DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL:-}
            TIMEOUT: ${TIMEOUT:-300}
            LOGIN_RETRY_MAX: ${LOGIN_RETRY_MAX:-3}
            LOGIN_RETRY_DELAY: ${LOGIN_RETRY_DELAY:-3}
            COOKIE_FILE: /app/data/cookies.json
        network_mode: "service:gluetun"
        volumes:
            - bot_data:/app/data
        restart: unless-stopped

    gluetun:
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun:/dev/net/tun
        environment:
            TZ: ${TZ:-UTC}
            VPN_SERVICE_PROVIDER: ${VPN_SERVICE_PROVIDER:-protonvpn}
            VPN_TYPE: ${VPN_TYPE:-wireguard}
            WIREGUARD_PRIVATE_KEY: ${PROTONVPN_PRIVATE_KEY:?error}
            SERVER_COUNTRIES: ${SERVER_COUNTRIES:-Netherlands,Canada,Japan,Norway,Singapore,Switzerland,Poland,Romania,Mexico,United States}
            FREE_ONLY: ${FREE_ONLY:-on}
            UPDATER_PERIOD: ${UPDATER_PERIOD:-72h}
        image: ghcr.io/qdm12/gluetun:v3.41
        restart: unless-stopped
        volumes:
            - gluetun_data:/gluetun

volumes:
    bot_data:
    gluetun_data:
